Create tests.yml
Avivsalem/BaseService pull request #2
Opened 2021-12-05 17:51 UTC by noamisraeli

2021-12-05 18:07 UTC, Avivsalem requested changes

2021-12-05 18:07 UTC, Avivsalem commented on .github/workflows/tests.yml
> +        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
test 3.7 and up.
no need for 3.5, 3.6

2021-12-05 18:07 UTC, Avivsalem commented on .github/workflows/tests.yml
> +        run: python setup.py install
why not pip install.

2021-12-05 18:10 UTC, noamisraeli commented on .github/workflows/tests.yml
> +        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
```suggestion
        python-version: [3.7, 3.8, 3.9]
```

2021-12-05 18:13 UTC, noamisraeli commented on .github/workflows/tests.yml
> +        run: python setup.py install
```suggestion
        run: python install .
```

2021-12-06 19:25 UTC, Avivsalem approved these changes

2021-12-06 19:26 UTC, merged